version: "3"
services:
  lb:
    image: 3dsinteractive/nginx:1.12
    depends_on:
      - mynginx1
      - mynginx2
    ports:
      - 8080:8080
      - 8443:8443
    restart: always
    volumes:
      - ./dockers/lb/logs:/opt/bitnami/nginx/logs
      - ./dockers/lb/nginx:/bitnami/nginx
  mynginx1:
    image: 3dsinteractive/mynginx:1.0
  mynginx2:
    image: 3dsinteractive/mynginx:1.0
