apiVersion: v1
kind: Service
metadata:
  name: kfk1
  namespace: basic-kafka
  labels:
    name: kfk1
spec:
  selector:
    name: kfk1
  ports:
  - name: kfk9092
    port: 9092
    protocol: TCP
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: kfk2
  namespace: basic-kafka
  labels:
    name: kfk2
spec:
  selector:
    name: kfk2
  ports:
  - name: kfk9092
    port: 9092
    protocol: TCP
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: kfk3
  namespace: basic-kafka
  labels:
    name: kfk3
spec:
  selector:
    name: kfk3
  ports:
  - name: kfk9092
    port: 9092
    protocol: TCP
  clusterIP: None