apiVersion: apps/v1
kind: Deployment
metadata:
  name: kfk1
  namespace: scale-service
  labels:
    name: kfk1
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: kfk1
  template:
    metadata:
      labels:
        name: kfk1
    spec:
      containers:
      - name: kfk1
        image: 3dsinteractive/kafka:2.0-custom
        imagePullPolicy: Always
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_PORT_NUMBER
          value: "9092"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: INSIDE://kfk1:9092
        - name: KAFKA_LISTENERS
          value: INSIDE://:9092
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_NUM_PARTITIONS
          value: "50"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zk1:2181,zk2:2181,zk3:2181
        - name: KAFKA_NUM_NETWORK_THREADS
          value: "8"
        - name: KAFKA_NUM_IO_THREADS
          value: "16"
        - name: KAFKA_SOCKET_SEND_BUFFER_BYTES
          value: "102400"
        - name: KAFKA_SOCKET_RECEIVE_BUFFER_BYTES
          value: "102400"
        - name: KAFKA_SOCKET_REQUEST_MAX_BYTES
          value: "104857600"
        - name: KAFKA_MAX_MESSAGE_BYTES
          value: "1000012"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: INSIDE:PLAINTEXT
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: INSIDE
        - name: KAFKA_HEAP_OPTS
          value: -Xmx1G -Xms1G
        resources:
          requests:
            memory: 500Mi
            cpu: 200m
          limits:
            memory: 1Gi
            cpu: 500m
        livenessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 300
        readinessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 30
          failureThreshold: 5
        ports:
        - containerPort: 9092
          name: kfk9092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kfk2
  namespace: scale-service
  labels:
    name: kfk2
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: kfk2
  template:
    metadata:
      labels:
        name: kfk2
    spec:
      containers:
      - name: kfk2
        image: 3dsinteractive/kafka:2.0-custom
        imagePullPolicy: Always
        env:
        - name: KAFKA_BROKER_ID
          value: "2"
        - name: KAFKA_PORT_NUMBER
          value: "9092"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: INSIDE://kfk2:9092
        - name: KAFKA_LISTENERS
          value: INSIDE://:9092
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_NUM_PARTITIONS
          value: "50"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zk1:2181,zk2:2181,zk3:2181
        - name: KAFKA_NUM_NETWORK_THREADS
          value: "8"
        - name: KAFKA_NUM_IO_THREADS
          value: "16"
        - name: KAFKA_SOCKET_SEND_BUFFER_BYTES
          value: "102400"
        - name: KAFKA_SOCKET_RECEIVE_BUFFER_BYTES
          value: "102400"
        - name: KAFKA_SOCKET_REQUEST_MAX_BYTES
          value: "104857600"
        - name: KAFKA_MAX_MESSAGE_BYTES
          value: "1000012"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: INSIDE:PLAINTEXT
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: INSIDE
        - name: KAFKA_HEAP_OPTS
          value: -Xmx1G -Xms1G
        resources:
          requests:
            memory: 500Mi
            cpu: 200m
          limits:
            memory: 1Gi
            cpu: 500m
        livenessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 300
        readinessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 30
          failureThreshold: 5
        ports:
        - containerPort: 9092
          name: kfk9092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kfk3
  namespace: scale-service
  labels:
    name: kfk3
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: kfk3
  template:
    metadata:
      labels:
        name: kfk3
    spec:
      containers:
      - name: kfk3
        image: 3dsinteractive/kafka:2.0-custom
        imagePullPolicy: Always
        env:
        - name: KAFKA_BROKER_ID
          value: "3"
        - name: KAFKA_PORT_NUMBER
          value: "9092"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: INSIDE://kfk3:9092
        - name: KAFKA_LISTENERS
          value: INSIDE://:9092
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_NUM_PARTITIONS
          value: "50"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zk1:2181,zk2:2181,zk3:2181
        - name: KAFKA_NUM_NETWORK_THREADS
          value: "8"
        - name: KAFKA_NUM_IO_THREADS
          value: "16"
        - name: KAFKA_SOCKET_SEND_BUFFER_BYTES
          value: "102400"
        - name: KAFKA_SOCKET_RECEIVE_BUFFER_BYTES
          value: "102400"
        - name: KAFKA_SOCKET_REQUEST_MAX_BYTES
          value: "104857600"
        - name: KAFKA_MAX_MESSAGE_BYTES
          value: "1000012"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: INSIDE:PLAINTEXT
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: INSIDE
        - name: KAFKA_HEAP_OPTS
          value: -Xmx1G -Xms1G
        resources:
          requests:
            memory: 500Mi
            cpu: 200m
          limits:
            memory: 1Gi
            cpu: 500m
        livenessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 300
        readinessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 30
          failureThreshold: 5
        ports:
        - containerPort: 9092
          name: kfk9092
---
apiVersion: v1
kind: Service
metadata:
  name: kfk1
  namespace: scale-service
  labels:
    name: kfk1
spec:
  selector:
    name: kfk1
  ports:
  - name: kfk9092
    port: 9092
    protocol: TCP
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: kfk2
  namespace: scale-service
  labels:
    name: kfk2
spec:
  selector:
    name: kfk2
  ports:
  - name: kfk9092
    port: 9092
    protocol: TCP
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: kfk3
  namespace: scale-service
  labels:
    name: kfk3
spec:
  selector:
    name: kfk3
  ports:
  - name: kfk9092
    port: 9092
    protocol: TCP
  clusterIP: None